import { Question } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    title: '현재 AI에 대한 경험과 가장 가까운 것을 선택해 주세요.',
    type: 'select',
    options: [
      { value: 'level_1', label: 'AI가 무엇을 할 수 있는지 거의 모른다' },
      { value: 'level_2', label: 'ChatGPT 같은 도구를 들어봤거나 한두 번 사용해 봤다' },
      { value: 'level_3', label: '검색, 글쓰기, 요약 등에 가끔 사용한다' },
      { value: 'level_4', label: '업무에 어느 정도 반복적으로 사용하고 있다' },
      { value: 'level_5', label: '여러 AI 도구를 적극적으로 사용하고 있다' },
    ],
  },
  {
    id: 'q2',
    title: '이번 AX 교육에 참여하면서 가장 기대하거나 궁금한 것은 무엇인가요?',
    type: 'select_with_detail',
    options: [
      { value: 'understand_ai', label: 'AI가 무엇을 할 수 있는지 알고 싶다' },
      { value: 'apply_work', label: '실제 업무에 AI를 사용해 보고 싶다' },
      { value: 'save_time', label: '일하는 시간을 줄이고 싶다' },
      { value: 'reduce_repeat', label: '반복되는 일을 줄이고 싶다' },
      { value: 'improve_quality', label: '글, 보고서, 기획안 등의 수준을 높이고 싶다' },
      { value: 'expand_ideas', label: '아이디어나 새로운 가능성을 넓히고 싶다' },
      { value: 'create_content', label: '이미지나 발표 자료를 직접 만들고 싶다' },
      { value: 'keep_up', label: '앞으로의 변화에 뒤처지지 않고 싶다' },
      { value: 'explore', label: '아직 잘 모르겠고 가능성을 살펴보고 싶다' },
      { value: 'other', label: '기타 (직접 입력)' },
    ],
    detailPrompt: '선택한 이유를 짧게 설명해 주세요. (선택 사항)',
    detailRequired: false,
  },
  {
    id: 'q3',
    title: '이번 교육을 통해 한 가지가 달라질 수 있다면, 무엇이 가장 달라졌으면 좋겠나요?',
    type: 'free',
    referenceExamples: [
      '일이 더 잘 정리되는 것',
      '일하는 시간이 줄어드는 것',
      '반복 업무가 줄어드는 것',
      '결과물이 더 좋아지는 것',
      '어려운 일을 쉽게 시작하는 것',
      '새로운 일을 할 수 있게 되는 것',
      'AI를 이해하고 자신 있게 사용하는 것',
    ],
  },
  {
    id: 'q4',
    title: '그 변화를 가장 먼저 적용해 보고 싶은 일은 무엇인가요?',
    type: 'select_with_detail',
    options: [
      { value: 'email', label: '이메일이나 메시지 작성' },
      { value: 'meeting', label: '회의 내용 정리' },
      { value: 'report', label: '보고서 작성' },
      { value: 'proposal', label: '기획안 또는 제안서 작성' },
      { value: 'research', label: '자료 조사와 비교' },
      { value: 'summary', label: '긴 문서 요약' },
      { value: 'schedule', label: '일정과 할 일 관리' },
      { value: 'ideation', label: '아이디어 만들기' },
      { value: 'presentation', label: '발표 자료 만들기' },
      { value: 'image', label: '이미지 만들기' },
      { value: 'data', label: '숫자나 데이터 정리' },
      { value: 'customer', label: '고객 문의나 응대' },
      { value: 'study', label: '개인적인 공부와 정보 정리' },
      { value: 'unknown', label: '아직 잘 모르겠다' },
      { value: 'other', label: '기타 (직접 입력)' },
    ],
    detailPrompt: '현재 그 일을 하면서 가장 불편한 점을 한 문장으로 알려주세요.',
    detailRequired: false,
  },
  {
    id: 'q5',
    title: 'AI가 그 일을 어느 정도까지 도와주기를 기대하시나요?',
    type: 'select',
    options: [
      { value: 'guidance', label: '무엇을 해야 할지 알려주는 정도' },
      { value: 'idea_support', label: '참고할 예시와 아이디어를 주는 정도' },
      { value: 'draft_generation', label: '결과물의 초안을 만들어 주는 정도' },
      { value: 'co_creation', label: '대부분을 만들고 내가 수정하는 정도' },
      { value: 'near_completion', label: '거의 완성된 결과물을 만들어 주는 정도' },
      { value: 'recurring_automation', label: '반복되는 일을 알아서 처리해 주는 정도' },
      { value: 'unknown', label: '아직 어느 정도가 가능한지 모르겠다' },
    ],
  },
  {
    id: 'q6',
    title: '어느 정도까지 달라지면 "AI를 배운 것이 실제로 도움이 됐다"고 느끼실 것 같나요?',
    type: 'select',
    options: [
      { value: 'level_1', label: 'AI가 무엇을 할 수 있는지 이해하면 충분하다' },
      { value: 'level_2', label: '간단한 일을 한 번 직접 해볼 수 있으면 좋겠다' },
      { value: 'level_3', label: '실제 업무 하나에 사용할 수 있으면 좋겠다' },
      { value: 'level_4', label: '업무에서 반복적으로 사용할 수 있으면 좋겠다' },
      { value: 'level_5', label: '시간이나 결과물에 분명한 변화가 생기면 좋겠다' },
      { value: 'level_6', label: '일하는 방식 자체가 달라지면 좋겠다' },
      { value: 'other', label: '기타 (직접 입력)' },
    ],
  },
  {
    id: 'q7',
    title: '교육 후 어떤 변화가 생기면 가장 만족스러울까요?',
    description: '최대 2개까지 선택할 수 있습니다.',
    type: 'select',
    maxSelect: 2,
    options: [
      { value: 'ask_ai', label: 'AI에게 원하는 내용을 어렵지 않게 요청할 수 있다' },
      { value: 'reduce_blank', label: '업무를 시작할 때의 막막함이 줄어든다' },
      { value: 'fast_draft', label: '글이나 문서의 초안을 빠르게 만들 수 있다' },
      { value: 'save_time', label: '업무 시간이 줄어든다' },
      { value: 'reduce_repeat', label: '반복되는 일 하나를 줄일 수 있다' },
      { value: 'better_quality', label: '결과물의 품질이 좋아진다' },
      { value: 'less_errors', label: '수정과 실수가 줄어든다' },
      { value: 'new_ideas', label: '새로운 아이디어나 대안을 만들 수 있다' },
      { value: 'new_tasks', label: '이전에는 하지 못했던 일을 직접 해볼 수 있다' },
      { value: 'keep_using', label: '실제 업무에서 계속 사용할 수 있다' },
      { value: 'other', label: '기타 (직접 입력)' },
    ],
  },
  {
    id: 'q8',
    title: '교육이 끝난 뒤 가장 먼저 직접 해보고 싶은 것은 무엇인가요?',
    type: 'select_with_detail',
    options: [
      { value: 'ask_answer', label: 'AI에게 질문하고 원하는 답을 얻어보기' },
      { value: 'draft_email', label: '이메일이나 글의 초안 만들기' },
      { value: 'summarize', label: '긴 자료를 요약하고 정리하기' },
      { value: 'write_report', label: '실제 업무 보고서나 기획안 만들기' },
      { value: 'brainstorm', label: '아이디어를 만들고 발전시키기' },
      { value: 'create_visual', label: '이미지나 발표 자료 만들기' },
      { value: 'organize', label: '일정과 할 일을 정리하기' },
      { value: 'reduce_repeat', label: '반복 업무를 줄일 방법 찾아보기' },
      { value: 'design_workflow', label: '내 업무에 맞는 AI 활용법 설계하기' },
      { value: 'unknown', label: '아직 잘 모르겠다' },
      { value: 'other', label: '기타 (직접 입력)' },
    ],
    detailPrompt: '실제로 적용해 보고 싶은 업무나 상황을 한 문장으로 적어주세요. (선택 사항)',
    detailRequired: false,
  },
];

export const ADDITIONAL_QUESTION = {
  id: 'additional',
  title: '강의의 방향이나 내용과 관련해 꼭 다뤄줬으면 하는 내용, 궁금한 점 또는 걱정되는 부분이 있다면 자유롭게 알려주세요.',
  type: 'free' as const,
  referenceExamples: [
    '너무 어렵지 않았으면 좋겠다',
    '실제 업무 사례가 많았으면 좋겠다',
    '직접 따라 해보는 시간이 필요하다',
    '어떤 AI 도구를 선택해야 하는지 궁금하다',
    'AI의 답을 어디까지 믿어도 되는지 궁금하다',
    '개인정보와 회사 자료 보안이 걱정된다',
    '무료와 유료 도구의 차이가 궁금하다',
  ],
};
